### ISSUE TITLE
password based auth for your-server

### ISSUE THREAD

**Issue by tkellen** [bocoup/learn-ssh#14]
Based on feedback from @susanjrobertson we should include some notes about what happens if you try to ssh as the user you created before `authorized_keys` are in place. It prompts for a password instead of outright failing to connect. If we prevented password based authentication this would be much clearer.

```
- name: disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart sshd
```
